### ISSUE TITLE
#BUG

### ISSUE THREAD

**Issue by THE-DSR** [AnonymousX1025/StringGenBot#14]
Current thread 0x00007fc977449740 (most recent call first):
<no Python frame>
ERROR: failed to build: exit status 1
exit status 51
Build failed ❌

**Comment by AnonymousX1025** [comment]
Please elaborate

**Comment by AnonymousX1025** [comment]
> Current thread 0x00007fc977449740 (most recent call first): ERROR: failed to build: exit status 1 exit status 51 Build failed ❌

Please explain the issue.

**Comment by THE-DSR** [comment]
> > Current thread 0x00007fc977449740 (most recent call first): ERROR: failed to build: exit status 1 exit status 51 Build failed ❌
> 
> Please explain the issue.

Check telegram
Please

**Comment by AnonymousX1025** [comment]
> > > Current thread 0x00007fc977449740 (most recent call first): ERROR: failed to build: exit status 1 exit status 51 Build failed ❌
> > 
> > 
> > Please explain the issue.
> 
> Check telegram Please

Please explain your issue at @DevilsHeavenMF on telegram
